using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Assets.SRC.ProceduralMapGeneration.ScriptableObjects
{
    [CreateAssetMenu(fileName = "Data", menuName = "ScriptableObjects/DirectionalTilesScriptableObject", order = 1)]
    public class DirectionalTilesScriptableObject : ScriptableObject
    {
        public GameObject N;
        public GameObject NE;
        public GameObject NS;
        public GameObject NW;
        public GameObject NT;
        public GameObject NB;
        public GameObject NES;
        public GameObject NESW;
        public GameObject NEWTB;
        public GameObject NESWT;
        public GameObject EWTB;
        public GameObject NESWB;
        public GameObject NESWBT;
        public GameObject NEW;
        public GameObject NEWT;
        public GameObject NEWB;
        public GameObject NET;
        public GameObject NETB;
        public GameObject NEB;
        public GameObject NEST;
        public GameObject NESTB;
        public GameObject NESB;
        public GameObject NSW;
        public GameObject NSWT;
        public GameObject NSWB;
        public GameObject NST;
        public GameObject NSTB;
        public GameObject NSB;
        public GameObject NSWTB;
        public GameObject NWT;
        public GameObject NWTB;
        public GameObject NWB;
        public GameObject NTB;
        public GameObject ES;
        public GameObject ESW;
        public GameObject ESWT;
        public GameObject ESWB;
        public GameObject ESWBT;
        public GameObject EW;
        public GameObject EWT;
        public GameObject EWB;
        public GameObject ET;
        public GameObject ETB;
        public GameObject EB;
        public GameObject EST;
        public GameObject ESTB;
        public GameObject ESB;
        public GameObject SW;
        public GameObject SWT;
        public GameObject SWB;
        public GameObject ST;
        public GameObject STB;
        public GameObject SB;
        public GameObject SWTB;
        public GameObject WT;
        public GameObject WTB;
        public GameObject WB;
        public GameObject TB;
        public GameObject S;
        public GameObject E;
        public GameObject SWBT;
        public GameObject W;
        public GameObject T;
        public GameObject B;

        public List<GameObject> RetunObjectsAsAList()
        {
            List<GameObject> retunObjects = new List<GameObject>();
            retunObjects.Add(NE);
            retunObjects.Add(NS);
            retunObjects.Add(NW);
            retunObjects.Add(NT);
            retunObjects.Add(NB);
            retunObjects.Add(NES);
            retunObjects.Add(NESW);
            retunObjects.Add(NEWTB);
            retunObjects.Add(NESWT);
            retunObjects.Add(EWTB);
            retunObjects.Add(NESWB);
            retunObjects.Add(NESWBT);
            retunObjects.Add(NEW);
            retunObjects.Add(NEWT);
            retunObjects.Add(NEWB);
            retunObjects.Add(NET);
            retunObjects.Add(NETB);
            retunObjects.Add(NEB);
            retunObjects.Add(NEST);
            retunObjects.Add(NESTB);
            retunObjects.Add(NESB);
            retunObjects.Add(NSW);
            retunObjects.Add(NSWT);
            retunObjects.Add(NSWB);
            retunObjects.Add(NST);
            retunObjects.Add(NSTB);
            retunObjects.Add(NSB);
            retunObjects.Add(NSWTB);
            retunObjects.Add(NWT);
            retunObjects.Add(NWTB);
            retunObjects.Add(NWB);
            retunObjects.Add(NTB);
            retunObjects.Add(ES);
            retunObjects.Add(ESW);
            retunObjects.Add(ESWT);
            retunObjects.Add(ESWB);
            retunObjects.Add(ESWBT);
            retunObjects.Add(EW);
            retunObjects.Add(EWT);
            retunObjects.Add(EWB);
            retunObjects.Add(ET);
            retunObjects.Add(ETB);
            retunObjects.Add(EB);
            retunObjects.Add(EST);
            retunObjects.Add(ESTB);
            retunObjects.Add(ESB);
            retunObjects.Add(SW);
            retunObjects.Add(SWT);
            retunObjects.Add(SWB);
            retunObjects.Add(ST);
            retunObjects.Add(STB);
            retunObjects.Add(SB);
            retunObjects.Add(SWTB);
            retunObjects.Add(WT);
            retunObjects.Add(WTB);
            retunObjects.Add(WB);
            retunObjects.Add(TB);
            retunObjects.Add(S);
            retunObjects.Add(E);
            retunObjects.Add(SWBT);
            retunObjects.Add(W);
            retunObjects.Add(T);
            retunObjects.Add(B);

            return retunObjects;
        }
    }
}
